#!/bin/bash

MYUSERNAME="user"
MYPASSWORD="password"
STARTOFSCRIPT=`date`

echo "$STARTOFSCRIPT"
echo "THE CURRENT USERNAME: $MYUSERNAME"
echo "THE CURRENT PASSWORD: $MYPASSWORD"

ENDOFSCRIPT=`date`
echo "$ENDOFSCRIPT"

